# Generated by Django 2.2.1 on 2019-07-02 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cname', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='车牌')),
                ('statime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入库时间')),
                ('endtime', models.DateTimeField(default=None, verbose_name='出库时间')),
                ('costs', models.FloatField(default=0, verbose_name='累计消费')),
            ],
        ),
    ]
